# Site settings

author: Loren
email: cooloren@163.com
github_username:  Loren1994
# twitter_username: twitter
# googleplus_username: google

head-title: Loren's blog
title: 一些微小的工作

baseurl: "/loren1994"    # the subpath of your site, "/blog"
url: ""

# footer 
description: "It is better to be a head of dog than a tail of a lion."

favo: "路漫漫其修远兮 吾将上下而求索"
descrpt: "ᕦ(･ㅂ･)ᕤ"


#
# Build settings
#

#exclude: [vendor]

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  highlight: true
  auto_ids:  true

sass:
  style: compressed

permalink: /posts/:categories/:title.html

paginate: 7
#paginate_path: 'page/:num'

gems: [jekyll-paginate, jekyll-last-modified-at, jemoji]


#
# Custom
#

# Color
# All css class, see: http://materializecss.com/color.html
header-color: "indigo lighten-1"
head-theme-color: "#5c6bc0"     # MUST in hex format, may the same as header-color. This color is for android chrome browser.

footer-color: "indigo lighten-1"
footer-button-color: "indigo lighten-2"
footer-link-color: "red-text text-accent-1"

share-button-color: "pink"
share-button-small-color: ""


##
#excerpt_separator: <!-- excerpt_end -->       # for post.excerpt

